name: Build using gradle

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Regular build
      if: ${{ env.TAG == 'refs/heads/master' }}
      run: ./gradlew build
      env:
        ORG_GRADLE_PROJECT_intellijPublishToken: ${{secrets.INTELLIJ_TOKEN}}
    - name: Deploy tag
      if: ${{ env.TAG != 'refs/heads/master' }}
      run: ./gradlew publishPlugin
      env:
        ORG_GRADLE_PROJECT_intellijPublishToken: ${{secrets.INTELLIJ_TOKEN}}
    - uses: actions/upload-artifact@v2
      with:
        path: build/distributions/*
