name: Build using gradle

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Set up JDK 11
#      uses: actions/setup-java@v2
#      with:
#        java-version: '11'
#        distribution: 'adopt'
#        cache: gradle
#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew
    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Regular build
      if: ${{ env.TAG == '' }}
      run: echo Regular build
    - name: Build tag
      if: ${{ env.TAG != '' }}
      run: echo Tag build

#    - name: Build with Gradle
#      run: ./gradlew build
#      env:
#        ORG_GRADLE_PROJECT_intellijPublishToken: ${{secrets.INTELLIJ_TOKEN}}
#    - uses: actions/upload-artifact@v2
#      with:
#        path: build/distributions/*
